/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GrammarQuizRouteImport } from './routes/grammarQuiz'
import { Route as HomeRouteImport } from './routes/home'
import { Route as InfoRouteImport } from './routes/info'
import { Route as JlptN1RouteImport } from './routes/jlpt-n1'
import { Route as JlptN2RouteImport } from './routes/jlpt-n2'
import { Route as JlptN3RouteImport } from './routes/jlpt-n3'
import { Route as JlptN4RouteImport } from './routes/jlpt-n4'
import { Route as JlptN5RouteImport } from './routes/jlpt-n5'
import { Route as KanjiQuizRouteImport } from './routes/kanjiQuiz'
import { Route as KanjisRouteImport } from './routes/kanjis'
import { Route as SelectLessonRouteImport } from './routes/selectLesson'
import { Route as SelectTypeRouteImport } from './routes/selectType'
import { Route as StudyRouteImport } from './routes/study'
import { Route as VocabRouteImport } from './routes/vocab'
import { Route as VocabQuizRouteImport } from './routes/vocabQuiz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarQuizRoute = GrammarQuizRouteImport.update({
  id: '/grammarQuiz',
  path: '/grammarQuiz',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const JlptN1Route = JlptN1RouteImport.update({
  id: '/jlpt-n1',
  path: '/jlpt-n1',
  getParentRoute: () => rootRouteImport,
} as any)
const JlptN2Route = JlptN2RouteImport.update({
  id: '/jlpt-n2',
  path: '/jlpt-n2',
  getParentRoute: () => rootRouteImport,
} as any)
const JlptN3Route = JlptN3RouteImport.update({
  id: '/jlpt-n3',
  path: '/jlpt-n3',
  getParentRoute: () => rootRouteImport,
} as any)
const JlptN4Route = JlptN4RouteImport.update({
  id: '/jlpt-n4',
  path: '/jlpt-n4',
  getParentRoute: () => rootRouteImport,
} as any)
const JlptN5Route = JlptN5RouteImport.update({
  id: '/jlpt-n5',
  path: '/jlpt-n5',
  getParentRoute: () => rootRouteImport,
} as any)
const KanjiQuizRoute = KanjiQuizRouteImport.update({
  id: '/kanjiQuiz',
  path: '/kanjiQuiz',
  getParentRoute: () => rootRouteImport,
} as any)
const KanjisRoute = KanjisRouteImport.update({
  id: '/kanjis',
  path: '/kanjis',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectLessonRoute = SelectLessonRouteImport.update({
  id: '/selectLesson',
  path: '/selectLesson',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectTypeRoute = SelectTypeRouteImport.update({
  id: '/selectType',
  path: '/selectType',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabRoute = VocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabQuizRoute = VocabQuizRouteImport.update({
  id: '/vocabQuiz',
  path: '/vocabQuiz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grammarQuiz': typeof GrammarQuizRoute
  '/home': typeof HomeRoute
  '/info': typeof InfoRoute
  '/jlpt-n1': typeof JlptN1Route
  '/jlpt-n2': typeof JlptN2Route
  '/jlpt-n3': typeof JlptN3Route
  '/jlpt-n4': typeof JlptN4Route
  '/jlpt-n5': typeof JlptN5Route
  '/kanjiQuiz': typeof KanjiQuizRoute
  '/kanjis': typeof KanjisRoute
  '/selectLesson': typeof SelectLessonRoute
  '/selectType': typeof SelectTypeRoute
  '/study': typeof StudyRoute
  '/vocab': typeof VocabRoute
  '/vocabQuiz': typeof VocabQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grammarQuiz': typeof GrammarQuizRoute
  '/home': typeof HomeRoute
  '/info': typeof InfoRoute
  '/jlpt-n1': typeof JlptN1Route
  '/jlpt-n2': typeof JlptN2Route
  '/jlpt-n3': typeof JlptN3Route
  '/jlpt-n4': typeof JlptN4Route
  '/jlpt-n5': typeof JlptN5Route
  '/kanjiQuiz': typeof KanjiQuizRoute
  '/kanjis': typeof KanjisRoute
  '/selectLesson': typeof SelectLessonRoute
  '/selectType': typeof SelectTypeRoute
  '/study': typeof StudyRoute
  '/vocab': typeof VocabRoute
  '/vocabQuiz': typeof VocabQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grammarQuiz': typeof GrammarQuizRoute
  '/home': typeof HomeRoute
  '/info': typeof InfoRoute
  '/jlpt-n1': typeof JlptN1Route
  '/jlpt-n2': typeof JlptN2Route
  '/jlpt-n3': typeof JlptN3Route
  '/jlpt-n4': typeof JlptN4Route
  '/jlpt-n5': typeof JlptN5Route
  '/kanjiQuiz': typeof KanjiQuizRoute
  '/kanjis': typeof KanjisRoute
  '/selectLesson': typeof SelectLessonRoute
  '/selectType': typeof SelectTypeRoute
  '/study': typeof StudyRoute
  '/vocab': typeof VocabRoute
  '/vocabQuiz': typeof VocabQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/grammarQuiz'
    | '/home'
    | '/info'
    | '/jlpt-n1'
    | '/jlpt-n2'
    | '/jlpt-n3'
    | '/jlpt-n4'
    | '/jlpt-n5'
    | '/kanjiQuiz'
    | '/kanjis'
    | '/selectLesson'
    | '/selectType'
    | '/study'
    | '/vocab'
    | '/vocabQuiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/grammarQuiz'
    | '/home'
    | '/info'
    | '/jlpt-n1'
    | '/jlpt-n2'
    | '/jlpt-n3'
    | '/jlpt-n4'
    | '/jlpt-n5'
    | '/kanjiQuiz'
    | '/kanjis'
    | '/selectLesson'
    | '/selectType'
    | '/study'
    | '/vocab'
    | '/vocabQuiz'
  id:
    | '__root__'
    | '/'
    | '/grammarQuiz'
    | '/home'
    | '/info'
    | '/jlpt-n1'
    | '/jlpt-n2'
    | '/jlpt-n3'
    | '/jlpt-n4'
    | '/jlpt-n5'
    | '/kanjiQuiz'
    | '/kanjis'
    | '/selectLesson'
    | '/selectType'
    | '/study'
    | '/vocab'
    | '/vocabQuiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GrammarQuizRoute: typeof GrammarQuizRoute
  HomeRoute: typeof HomeRoute
  InfoRoute: typeof InfoRoute
  JlptN1Route: typeof JlptN1Route
  JlptN2Route: typeof JlptN2Route
  JlptN3Route: typeof JlptN3Route
  JlptN4Route: typeof JlptN4Route
  JlptN5Route: typeof JlptN5Route
  KanjiQuizRoute: typeof KanjiQuizRoute
  KanjisRoute: typeof KanjisRoute
  SelectLessonRoute: typeof SelectLessonRoute
  SelectTypeRoute: typeof SelectTypeRoute
  StudyRoute: typeof StudyRoute
  VocabRoute: typeof VocabRoute
  VocabQuizRoute: typeof VocabQuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammarQuiz': {
      id: '/grammarQuiz'
      path: '/grammarQuiz'
      fullPath: '/grammarQuiz'
      preLoaderRoute: typeof GrammarQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jlpt-n1': {
      id: '/jlpt-n1'
      path: '/jlpt-n1'
      fullPath: '/jlpt-n1'
      preLoaderRoute: typeof JlptN1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jlpt-n2': {
      id: '/jlpt-n2'
      path: '/jlpt-n2'
      fullPath: '/jlpt-n2'
      preLoaderRoute: typeof JlptN2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jlpt-n3': {
      id: '/jlpt-n3'
      path: '/jlpt-n3'
      fullPath: '/jlpt-n3'
      preLoaderRoute: typeof JlptN3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jlpt-n4': {
      id: '/jlpt-n4'
      path: '/jlpt-n4'
      fullPath: '/jlpt-n4'
      preLoaderRoute: typeof JlptN4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jlpt-n5': {
      id: '/jlpt-n5'
      path: '/jlpt-n5'
      fullPath: '/jlpt-n5'
      preLoaderRoute: typeof JlptN5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanjiQuiz': {
      id: '/kanjiQuiz'
      path: '/kanjiQuiz'
      fullPath: '/kanjiQuiz'
      preLoaderRoute: typeof KanjiQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanjis': {
      id: '/kanjis'
      path: '/kanjis'
      fullPath: '/kanjis'
      preLoaderRoute: typeof KanjisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selectLesson': {
      id: '/selectLesson'
      path: '/selectLesson'
      fullPath: '/selectLesson'
      preLoaderRoute: typeof SelectLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selectType': {
      id: '/selectType'
      path: '/selectType'
      fullPath: '/selectType'
      preLoaderRoute: typeof SelectTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocab': {
      id: '/vocab'
      path: '/vocab'
      fullPath: '/vocab'
      preLoaderRoute: typeof VocabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabQuiz': {
      id: '/vocabQuiz'
      path: '/vocabQuiz'
      fullPath: '/vocabQuiz'
      preLoaderRoute: typeof VocabQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GrammarQuizRoute: GrammarQuizRoute,
  HomeRoute: HomeRoute,
  InfoRoute: InfoRoute,
  JlptN1Route: JlptN1Route,
  JlptN2Route: JlptN2Route,
  JlptN3Route: JlptN3Route,
  JlptN4Route: JlptN4Route,
  JlptN5Route: JlptN5Route,
  KanjiQuizRoute: KanjiQuizRoute,
  KanjisRoute: KanjisRoute,
  SelectLessonRoute: SelectLessonRoute,
  SelectTypeRoute: SelectTypeRoute,
  StudyRoute: StudyRoute,
  VocabRoute: VocabRoute,
  VocabQuizRoute: VocabQuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
